/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca1java;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ataturkoglu
 */
public class feedbackGUI extends javax.swing.JFrame {

    private ArrayList<inheritance> feedbacks;
    /**
     * Creates new form feedbackGUI
     */
    public feedbackGUI() {
        initComponents();
        feedbacks = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedPageLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        feedbackLb = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        feedbackPane = new javax.swing.JScrollPane();
        feedbackTf = new javax.swing.JTextArea();
        feedbackBtn = new javax.swing.JButton();
        navBar8 = new javax.swing.JMenuBar();
        teacherMenu8 = new javax.swing.JMenu();
        teacherItem8 = new javax.swing.JMenuItem();
        feedbackMenu = new javax.swing.JMenu();
        feedbackItem = new javax.swing.JMenuItem();
        mathMenu = new javax.swing.JMenu();
        mathItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        feedPageLb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        feedPageLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        feedPageLb.setText("Give us a feedback");

        nameLb.setText("Name:");

        emailLb.setText("Email:");

        feedbackLb.setText("Feedback:");

        feedbackTf.setColumns(20);
        feedbackTf.setLineWrap(true);
        feedbackTf.setRows(5);
        feedbackPane.setViewportView(feedbackTf);

        feedbackBtn.setText("Submit");
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });

        teacherMenu8.setText("Volunteer Teacher");

        teacherItem8.setText("Volunteer Teacher");
        teacherItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherItem8ActionPerformed(evt);
            }
        });
        teacherMenu8.add(teacherItem8);

        navBar8.add(teacherMenu8);

        feedbackMenu.setText("Feedback");

        feedbackItem.setText("Feedback");
        feedbackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackItemActionPerformed(evt);
            }
        });
        feedbackMenu.add(feedbackItem);

        navBar8.add(feedbackMenu);

        mathMenu.setText("Math Game");

        mathItem.setText("Math Game");
        mathItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathItemActionPerformed(evt);
            }
        });
        mathMenu.add(mathItem);

        navBar8.add(mathMenu);

        setJMenuBar(navBar8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedPageLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(feedbackLb)
                    .addComponent(emailLb)
                    .addComponent(nameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailTf)
                    .addComponent(nameTf)
                    .addComponent(feedbackPane, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(feedbackBtn)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(feedPageLb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLb)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLb)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedbackLb)
                    .addComponent(feedbackPane, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(feedbackBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        // TODO add your handling code here:
        if (nameTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the name field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (emailTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the email field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (feedbackTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the feedback field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Thank You!");
             feedback myfeedback = new feedback();
            myfeedback.setName(nameTf.getText());
            myfeedback.setEmail(emailTf.getText());
            myfeedback.setFeedback(feedbackTf.getText());
            

        
            feedbacks.add(myfeedback);

            File f;
            FileOutputStream fStream;
            ObjectOutputStream oStream;

            try {
                f = new File("feedbacks.dat");
                fStream = new FileOutputStream(f);
                oStream = new ObjectOutputStream(fStream);

                oStream.writeObject(feedbacks);
                oStream.close();
            } catch (IOException e) {
                System.out.println(e);
            }

            nameTf.setText("");
            emailTf.setText("");
            feedbackTf.setText("");
        }

        
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void teacherItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherItem8ActionPerformed
        // TODO add your handling code here:
        teacherGUI appGUI = new teacherGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_teacherItem8ActionPerformed

    private void feedbackItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackItemActionPerformed
        // TODO add your handling code here:
        feedbackGUI appGUI = new feedbackGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_feedbackItemActionPerformed

    private void mathItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathItemActionPerformed
        // TODO add your handling code here:
        mathGUI appGUI = new mathGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mathItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedbackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLb;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel feedPageLb;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JMenuItem feedbackItem;
    private javax.swing.JLabel feedbackLb;
    private javax.swing.JMenu feedbackMenu;
    private javax.swing.JScrollPane feedbackPane;
    private javax.swing.JTextArea feedbackTf;
    private javax.swing.JMenuItem mathItem;
    private javax.swing.JMenu mathMenu;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JMenuBar navBar8;
    private javax.swing.JMenuItem teacherItem8;
    private javax.swing.JMenu teacherMenu8;
    // End of variables declaration//GEN-END:variables
}
