/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca1java;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ataturkoglu
 */
public class mathGUI extends javax.swing.JFrame {

    /**
     * Creates new form mathGUI
     */
    math myGame = new math();

    public mathGUI() {
        initComponents();
        level1Btn.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mathBtnGroup = new javax.swing.ButtonGroup();
        mathLb = new javax.swing.JLabel();
        level1Btn = new javax.swing.JRadioButton();
        level2Btn = new javax.swing.JRadioButton();
        level3Btn = new javax.swing.JRadioButton();
        nameLb = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        scorePane = new javax.swing.JScrollPane();
        scoreTa = new javax.swing.JTextArea();
        top10Lb = new javax.swing.JLabel();
        scoreTf = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        answerTf = new javax.swing.JTextField();
        questionTf = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        warningLb = new javax.swing.JLabel();
        navBar1 = new javax.swing.JMenuBar();
        teacherMenu1 = new javax.swing.JMenu();
        teacherItem1 = new javax.swing.JMenuItem();
        feedbackMenu = new javax.swing.JMenu();
        feedbackItem = new javax.swing.JMenuItem();
        mathMenu = new javax.swing.JMenu();
        mathItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mathLb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        mathLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mathLb.setText("Math Game");

        mathBtnGroup.add(level1Btn);
        level1Btn.setText("Level 1");
        level1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1BtnActionPerformed(evt);
            }
        });

        mathBtnGroup.add(level2Btn);
        level2Btn.setText("Level 2");
        level2Btn.setToolTipText("");
        level2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2BtnActionPerformed(evt);
            }
        });

        mathBtnGroup.add(level3Btn);
        level3Btn.setText("Level 3");
        level3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3BtnActionPerformed(evt);
            }
        });

        nameLb.setText("Name:");

        scoreTa.setEditable(false);
        scoreTa.setColumns(20);
        scoreTa.setLineWrap(true);
        scoreTa.setRows(5);
        scoreTa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scorePane.setViewportView(scoreTa);

        top10Lb.setText("Top 10 Scores");

        scoreTf.setEditable(false);
        scoreTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTfActionPerformed(evt);
            }
        });

        submitBtn.setText("submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        questionTf.setEditable(false);
        questionTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionTfActionPerformed(evt);
            }
        });

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        warningLb.setText("• If u want the play with diffirent level press start again");

        teacherMenu1.setText("Volunteer Teacher");

        teacherItem1.setText("Volunteer Teacher");
        teacherItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherItem1ActionPerformed(evt);
            }
        });
        teacherMenu1.add(teacherItem1);

        navBar1.add(teacherMenu1);

        feedbackMenu.setText("Feedback");

        feedbackItem.setText("Feedback");
        feedbackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackItemActionPerformed(evt);
            }
        });
        feedbackMenu.add(feedbackItem);

        navBar1.add(feedbackMenu);

        mathMenu.setText("Math Game");

        mathItem.setText("Math Game");
        mathItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathItemActionPerformed(evt);
            }
        });
        mathMenu.add(mathItem);

        navBar1.add(mathMenu);

        setJMenuBar(navBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mathLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scoreTf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(answerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(questionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(scorePane, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(level1Btn)
                                .addGap(18, 18, 18)
                                .addComponent(level2Btn)
                                .addGap(18, 18, 18)
                                .addComponent(level3Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(top10Lb)
                                .addGap(13, 13, 13)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mathLb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level1Btn)
                    .addComponent(level2Btn)
                    .addComponent(level3Btn)
                    .addComponent(top10Lb))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scorePane, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLb)
                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startBtn))
                        .addGap(30, 30, 30)
                        .addComponent(scoreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(warningLb)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionTfActionPerformed

    private void level1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1BtnActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_level1BtnActionPerformed

    private void level2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level2BtnActionPerformed

    private void level3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3BtnActionPerformed
        // TODO add your handling code here:*
    }//GEN-LAST:event_level3BtnActionPerformed

    private void scoreTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreTfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_scoreTfActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:

        if (nameTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the name field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            scoreTf.setText(" ");
            if (level1Btn.isSelected()) {
                myGame.setLevel(1);
            } else if (level2Btn.isSelected()) {
                myGame.setLevel(2);
            } else if (level3Btn.isSelected()) {
                myGame.setLevel(3);
            }
            myGame.setPlayerName(nameTf.getText());
            myGame.questionGenerate();
            questionTf.setText(myGame.getQuestion());
            nameTf.setText(" ");
            level1Btn.setEnabled(false);
            level2Btn.setEnabled(false);
            level3Btn.setEnabled(false);
        }
    }//GEN-LAST:event_startBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        if (myGame.check(Integer.parseInt(answerTf.getText()))) {
            questionTf.setText(myGame.getQuestion());
            answerTf.setText("");
            scoreTf.setText("your score is: " + myGame.getCurrentScore());
        } else {
            questionTf.setText(" ");
            level1Btn.setEnabled(true);
            level2Btn.setEnabled(true);
            level3Btn.setEnabled(true);
            answerTf.setText("");
            scoreTf.setText("GAME OVER last score: " + myGame.getCurrentScore());

            StringBuilder scoresText = new StringBuilder();
            ArrayList<String> scores = myGame.playerScores(); // Skorları bir kere al

            for (int i = 0; i < scores.size(); i++) {
                scoresText.append(i + 1).append(". ").append(scores.get(i)).append("\n");
            }

            scoreTa.setText(scoresText.toString());

        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void teacherItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherItem1ActionPerformed
        // TODO add your handling code here:
        teacherGUI appGUI = new teacherGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_teacherItem1ActionPerformed

    private void feedbackItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackItemActionPerformed
        // TODO add your handling code here:
        feedbackGUI appGUI = new feedbackGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_feedbackItemActionPerformed

    private void mathItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathItemActionPerformed
        // TODO add your handling code here:
        mathGUI appGUI = new mathGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mathItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerTf;
    private javax.swing.JMenuItem feedbackItem;
    private javax.swing.JMenu feedbackMenu;
    private javax.swing.JRadioButton level1Btn;
    private javax.swing.JRadioButton level2Btn;
    private javax.swing.JRadioButton level3Btn;
    private javax.swing.ButtonGroup mathBtnGroup;
    private javax.swing.JMenuItem mathItem;
    private javax.swing.JLabel mathLb;
    private javax.swing.JMenu mathMenu;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JMenuBar navBar1;
    private javax.swing.JTextField questionTf;
    private javax.swing.JScrollPane scorePane;
    private javax.swing.JTextArea scoreTa;
    private javax.swing.JTextField scoreTf;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JMenuItem teacherItem1;
    private javax.swing.JMenu teacherMenu1;
    private javax.swing.JLabel top10Lb;
    private javax.swing.JLabel warningLb;
    // End of variables declaration//GEN-END:variables
}
