/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca1java;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ataturkoglu
 */
public class teacherGUI extends javax.swing.JFrame {

    private ArrayList<inheritance> teachers;

    /**
     * Creates new form CA_GUI_V1
     */
    public teacherGUI() {

        initComponents();
        teachers = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherBtnGroup = new javax.swing.ButtonGroup();
        formLb = new javax.swing.JLabel();
        subjectLb = new javax.swing.JLabel();
        locationLb = new javax.swing.JLabel();
        ageLb = new javax.swing.JLabel();
        expLb = new javax.swing.JLabel();
        infoLb = new javax.swing.JLabel();
        expPane = new javax.swing.JScrollPane();
        expTf = new javax.swing.JTextArea();
        infoPane = new javax.swing.JScrollPane();
        infoTf = new javax.swing.JTextArea();
        subjectTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        locationTf = new javax.swing.JTextField();
        confirm = new javax.swing.JCheckBox();
        submitBtn = new javax.swing.JButton();
        longBtn = new javax.swing.JRadioButton();
        shortBtn = new javax.swing.JRadioButton();
        nameLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        displayBtn = new javax.swing.JButton();
        navBar = new javax.swing.JMenuBar();
        teacherMenu = new javax.swing.JMenu();
        teacherItem = new javax.swing.JMenuItem();
        feedbackMenu = new javax.swing.JMenu();
        feedbackItem = new javax.swing.JMenuItem();
        mathMenu = new javax.swing.JMenu();
        mathItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formLb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        formLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLb.setText("Teacher Form");

        subjectLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjectLb.setText("Subject:");

        locationLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locationLb.setText("Location:");

        ageLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLb.setText("Age:");

        expLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        expLb.setText("Experience:");

        infoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLb.setText("Other information:");

        expTf.setColumns(20);
        expTf.setLineWrap(true);
        expTf.setRows(5);
        expPane.setViewportView(expTf);

        infoTf.setColumns(20);
        infoTf.setLineWrap(true);
        infoTf.setRows(5);
        infoPane.setViewportView(infoTf);

        subjectTf.setSize(new java.awt.Dimension(78, 20));

        ageTf.setSize(new java.awt.Dimension(78, 20));

        locationTf.setSize(new java.awt.Dimension(78, 20));

        confirm.setText("I confirm that I want to become a volunteer teacher");
        confirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        teacherBtnGroup.add(longBtn);
        longBtn.setText("Long Time (1 Year)");
        longBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        longBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longBtnActionPerformed(evt);
            }
        });

        teacherBtnGroup.add(shortBtn);
        shortBtn.setText("Short Time (1 Month)");
        shortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortBtnActionPerformed(evt);
            }
        });

        nameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLb.setText("Name:");

        emailLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLb.setText("Email:");

        nameTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        teacherMenu.setText("Volunteer Teacher");

        teacherItem.setText("Volunteer Teacher");
        teacherItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherItemActionPerformed(evt);
            }
        });
        teacherMenu.add(teacherItem);

        navBar.add(teacherMenu);

        feedbackMenu.setText("Feedback");

        feedbackItem.setText("Feedback");
        feedbackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackItemActionPerformed(evt);
            }
        });
        feedbackMenu.add(feedbackItem);

        navBar.add(feedbackMenu);

        mathMenu.setText("Math Game");

        mathItem.setText("Math Game");
        mathItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathItemActionPerformed(evt);
            }
        });
        mathMenu.add(mathItem);

        navBar.add(mathMenu);

        setJMenuBar(navBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(confirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(longBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(shortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(infoLb)
                                .addComponent(subjectLb)
                                .addComponent(ageLb)
                                .addComponent(expLb)
                                .addComponent(locationLb)
                                .addComponent(emailLb))
                            .addComponent(nameLb, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(expPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(subjectTf)
                                    .addComponent(locationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(emailTf)
                            .addComponent(nameTf))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(formLb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLb)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectLb)
                    .addComponent(subjectTf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLb)
                    .addComponent(locationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLb)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expLb)
                    .addComponent(expPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLb)
                    .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortBtn)
                    .addComponent(longBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(displayBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherItemActionPerformed
        // TODO add your handling code here:
        teacherGUI appGUI = new teacherGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_teacherItemActionPerformed

    private void mathItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathItemActionPerformed
        // TODO add your handling code here:
        mathGUI appGUI = new mathGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mathItemActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (nameTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the name field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (emailTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the email field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (subjectTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the subject field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (locationTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the location field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (ageTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the age field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (expTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the experience field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (infoTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the other information field.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!confirm.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please tick the checkbox.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Thank You!");
            // Tüm alanlar doldurulduysa ve onay kutusu işaretlendiyse, form işlemlerini yap
            // Form işleme kodları burada yer alır...
            teacher myTeacher = new teacher();
            myTeacher.setName(nameTf.getText());
            myTeacher.setEmail(emailTf.getText());
            myTeacher.setSubject(subjectTf.getText());
            myTeacher.setLocation(locationTf.getText());
            myTeacher.setAge(Integer.parseInt(ageTf.getText()));
            myTeacher.setExperience(expTf.getText());
            myTeacher.setOther_info(infoTf.getText());

            if (longBtn.isSelected()) {
                myTeacher.setTimeType("Long Term");
            } else if (shortBtn.isSelected()) {
                myTeacher.setTimeType("Short Term");
            }
            teachers.add(myTeacher);

            File f;
            FileOutputStream fStream;
            ObjectOutputStream oStream;

            try {
                f = new File("teachers.dat");
                fStream = new FileOutputStream(f);
                oStream = new ObjectOutputStream(fStream);

                oStream.writeObject(teachers);
                oStream.close();
            } catch (IOException e) {
                System.out.println(e);
            }

            nameTf.setText("");
            emailTf.setText("");
            subjectTf.setText("");
            locationTf.setText("");
            ageTf.setText("");
            expTf.setText("");
            infoTf.setText("");
            confirm.setSelected(false);
            teacherBtnGroup.clearSelection();
        }


    }//GEN-LAST:event_submitBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            f = new File("teachers.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);

            teachers = (ArrayList<inheritance>) oStream.readObject();
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
        }

        StringBuilder detailsBuilder = new StringBuilder();
        for (inheritance myTeacher : teachers) {
            detailsBuilder.append(myTeacher.getDetails()).append("\n" + "\n");
        }

        JTextArea textArea = new JTextArea(detailsBuilder.toString());
        textArea.setWrapStyleWord(true);

        textArea.setEditable(false);
        textArea.setColumns(30);
        textArea.setRows(10);

        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(null, scrollPane);

    }//GEN-LAST:event_displayBtnActionPerformed

    private void longBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longBtnActionPerformed

    private void shortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortBtnActionPerformed

    private void feedbackItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackItemActionPerformed
        // TODO add your handling code here:
        feedbackGUI appGUI = new feedbackGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_feedbackItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLb;
    private javax.swing.JTextField ageTf;
    private javax.swing.JCheckBox confirm;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel emailLb;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel expLb;
    private javax.swing.JScrollPane expPane;
    private javax.swing.JTextArea expTf;
    private javax.swing.JMenuItem feedbackItem;
    private javax.swing.JMenu feedbackMenu;
    private javax.swing.JLabel formLb;
    private javax.swing.JLabel infoLb;
    private javax.swing.JScrollPane infoPane;
    private javax.swing.JTextArea infoTf;
    private javax.swing.JLabel locationLb;
    private javax.swing.JTextField locationTf;
    private javax.swing.JRadioButton longBtn;
    private javax.swing.JMenuItem mathItem;
    private javax.swing.JMenu mathMenu;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JMenuBar navBar;
    private javax.swing.JRadioButton shortBtn;
    private javax.swing.JLabel subjectLb;
    private javax.swing.JTextField subjectTf;
    private javax.swing.JButton submitBtn;
    private javax.swing.ButtonGroup teacherBtnGroup;
    private javax.swing.JMenuItem teacherItem;
    private javax.swing.JMenu teacherMenu;
    // End of variables declaration//GEN-END:variables
}
